eureka:
  client:
    serviceUrl:
      register-with-eureka: false
      fetch-registry: false
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: 'api-service'
  cloud:
    config:
      enabled: false

server:
  port: 8084

application:
  admin-service-uri: lb://ADMIN-SERVICE



