eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

spring:
  application:
    name: 'api-service'
  cloud:
    config:
      enabled: false

server:
  port: ${SERVER_PORT}

application:
  admin-service-name: ${ADMIN-SERVICE}
