eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: 'api-service'
  cloud:
    config:
      enabled: false

server:
  port: 8084

application:
  admin-service-name: lb://admin-service



