eureka:
  client:
    serviceUrl:
      register-with-eureka: false
      fetch-registry: false
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

spring:
  application:
    name: 'api-service'
  cloud:
    config:
      enabled: false

server:
  port: ${SERVER_PORT}

application:
  admin-service-uri: lb://ADMIN-SERVICE
